### ISSUE TITLE
definire meglio la licenza cc

### ISSUE THREAD

**Issue by napo** [albertotn/open-trentino#4]
nel testo scrivi "rilasciate tramite licenza CC", anche se c'è il logo sotto, è meglio scrivere "Creative Commons Attribution - CC-BY"
inoltre va definita anche come deve essere fatta l'attribuzione.
Consiglio di andare qui
https://creativecommons.org/choose/?lang=it

**Comment by albertotn** [comment]
Assegno a @mirkoperillo  per seguire la questione
